//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvIssue
    {
        public long Id { get; set; }
        public string IssueNo { get; set; }
        public string IssueDate { get; set; }
        public Nullable<long> IssueTo { get; set; }
        public Nullable<long> IssueBy { get; set; }
        public string Description { get; set; }
        public string IssuePlace { get; set; }
    }
}
