//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public decimal GST { get; set; }
        public decimal NetTotal { get; set; }
        public string PaymentType { get; set; }
        public decimal ServiceCharges { get; set; }
        public bool IsSentToPRA { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
