//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvReturnDetail
    {
        public long Id { get; set; }
        public Nullable<long> InvReturnId { get; set; }
        public Nullable<long> InventoryItemId { get; set; }
        public Nullable<double> Quantity { get; set; }
    }
}
