//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Invoices = new HashSet<Invoice>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.SCWTimers = new HashSet<SCWTimer>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> OrderDateTime { get; set; }
        public Nullable<System.DateTime> ExpectedServingTime { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<long> StatusId { get; set; }
        public string TableNumber { get; set; }
        public Nullable<long> WaiterId { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<decimal> DiscountValue { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> NetTotal { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Shift { get; set; }
        public string Location { get; set; }
        public Nullable<int> Pax { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCWTimer> SCWTimers { get; set; }
    }
}
